using System.Threading;
using UnityEditor;
using UnityEngine;

public class InteractiveObject : MonoBehaviour
{
    [SerializeField]
    private Camera playerCamera;

    [Header("��ȣ�ۿ� �Ÿ�")]
    [SerializeField]
    private float InteractionDistance = 5f;

    [Header("��ȣ�ۿ� ������Ʈ")]
    [SerializeField]
    private GameObject LeftMonitor;

    [SerializeField]
    private GameObject CenterMonitor;

    [SerializeField]
    private GameObject RightMonitor;

    [SerializeField]
    private GameObject Tablet;

    [SerializeField]
    private GameObject ManualObject;

    [SerializeField]
    private GameObject BarrelObject;//Pills Obj
    [SerializeField]
    private GameObject CrossingGatObject;//Crossing gate Obj
    [SerializeField]
    private GameObject FeedBarObject;//FeedBar Obj

    private GameObject rayCollisionObject;

    [SerializeField]
    private CCTVManager cctvManager;

    [SerializeField]
    private TabletManager testManager;

    [SerializeField]
    private ManualManager manualManager;

    [SerializeField]
    private LayerMask outlineLayerMask;

    private MeshRenderer curOutlineScale = null;

    private MaterialPropertyBlock outlineBlock;

    [SerializeField]
    private string outlineProperty = "_Scale";

    private float offOutlineScale = 0f;

    private float onOutlineScale = 1.05f;

    private bool isOnRay = true;

    private Canvas curInteractUI = null;

    private void Start()
    {
        outlineBlock = new MaterialPropertyBlock();
    }

    // Update is called once per frame
    void Update()
    {
        InteractionObject();

        if (cctvManager.isOnCCTV || testManager.isOnTablet || !isOnRay || manualManager.isOnManual)
        {
            ShowOutLine(null);
        }

        if (Input.GetKeyDown(KeyCode.F) && rayCollisionObject != null && !cctvManager.IsMoving() && !testManager.IsMoving() && !manualManager.IsMoving())
        {
            if (rayCollisionObject == LeftMonitor)
            {
                InteractLeftMonitor();
            }
            else if (rayCollisionObject == CenterMonitor)
            {
                InteractCenterMonitor();
            }
            else if (rayCollisionObject == RightMonitor)
            {
                InteractRightMonitor();
            }
            else if (rayCollisionObject == Tablet)
            {
                InteractTablet();
            }
            else if (rayCollisionObject == ManualObject)
            {
                InteractManual();
            }
            else if(rayCollisionObject == BarrelObject)
            {
                InteractBarrel();
            }
            else if(rayCollisionObject == CrossingGatObject)
            {
                InteractCrossingGat();
            }
            else if(rayCollisionObject == FeedBarObject)
            {
                InteractFeedBar();
            }
        }
    }

    void InteractionObject()
    {
        // ray�� ��ũ�� ���� ������ �߾��� �� ���߾�
        Ray ray = playerCamera.ScreenPointToRay(new Vector3(Screen.width / 2, Screen.height / 2));
        Debug.DrawRay(ray.origin, ray.direction);
        RaycastHit hit; // Hit ���� ������Ʈ�� hit�� ����

        GameObject outLineObject = null;

        if (Physics.Raycast(ray, out hit, InteractionDistance, outlineLayerMask))
        {
            GameObject hitObject = hit.collider.gameObject;
            if (hitObject == LeftMonitor || hitObject == CenterMonitor ||
                hitObject == RightMonitor || hitObject == Tablet || hitObject == ManualObject || hitObject == BarrelObject)
            {
                rayCollisionObject = hitObject;
                outLineObject = hitObject;
            }
            // This Is SetOutline Conditional
            else if (hitObject == CrossingGatObject)
            {
                if (CrossingGatObject.transform.parent.GetComponent<CrossingGats>().isCrossingGateShutDown)
                {
                    rayCollisionObject = hitObject;
                    outLineObject = hitObject;
                }
            }
            else if (hitObject == FeedBarObject)
            {
                rayCollisionObject = hitObject;
                outLineObject = hitObject;
            }
            else
            {
                rayCollisionObject = null;
            }
        }
        else
        {
            rayCollisionObject = null;
        }

        ShowOutLine(outLineObject);
    }

    void InteractLeftMonitor()
    {
        cctvManager.CCTV_Pos_Rot(CCTVLocation.Left);
        Debug.Log("��");
    }
    void InteractCenterMonitor()
    {
        cctvManager.CCTV_Pos_Rot(CCTVLocation.Center);
        Debug.Log("��");
    }

    void InteractRightMonitor()
    {
        cctvManager.CCTV_Pos_Rot(CCTVLocation.Right);
        Debug.Log("��");
    }
    void InteractTablet()
    {
        testManager.MovingTabletView();
    }
    private void InteractManual()
    {
        if(DaySystem.Instance.GetNowDay() == 1)
        {
            if (GameManager.Instance.isGameStart) return;

            GameManager.Instance.isGameStop = false;
            GameManager.Instance.isGameStart = true;

            GameManager.Instance.anomalySystem.specialObjects[3].GetComponent<Animator>().Play("Close");
            GameManager.Instance.anomalySystem.specialObjects[2].GetComponent<Animator>().Play("Close");
        }

        manualManager.MovingManualView();
    }
    private void InteractBarrel()
    {
        GameManager.Instance.anomalySystem.ClearSpecial();
    }
    private void InteractCrossingGat()
    {
        CrossingGats gatComp = CrossingGatObject.transform.parent.GetComponent<CrossingGats>();
        if (gatComp)
            gatComp.TryActionEvent();
        GameManager.Instance.anomalySystem.ClearSpecial();
    }
    private void InteractFeedBar()
    {
        GameManager.Instance.anomalySystem.ClearSpecial();
    }

    private void ShowOutLine(GameObject outlineable)
    {
        MeshRenderer newOutLineObject = null;
        Canvas newInteractUI = null;

        if (outlineable != null)
        {
            newOutLineObject = outlineable.GetComponent<MeshRenderer>();
            Transform parent = outlineable.transform.parent;
            if (parent != null)
            {
                newInteractUI = parent.GetComponentInChildren<Canvas>(true);
            }
        }

        if (newOutLineObject != curOutlineScale)
        {
            if (curOutlineScale != null)
            {
                outlineBlock.SetFloat(outlineProperty, offOutlineScale);
                curOutlineScale.SetPropertyBlock(outlineBlock, 1);

                Debug.Log("���");
            }
            if (curInteractUI != null)
            {
                curInteractUI.gameObject.SetActive(false);
            }

            if (newOutLineObject != null)
            {
                outlineBlock.SetFloat(outlineProperty, onOutlineScale);
                newOutLineObject.SetPropertyBlock(outlineBlock, 1);

                if (newInteractUI != null)
                {
                    newInteractUI.gameObject.SetActive(true);
                }
                Debug.Log("�ѱ�");
            }

            curOutlineScale = newOutLineObject;
            curInteractUI = newInteractUI;
        }

    }
    public void SetRay(bool ray)
    {
        isOnRay = ray;

        if (!isOnRay)
        {
            ShowOutLine(null);
        }
    }
}
